// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:memento/credential.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /*
   * In case you are wondering...commit history, right?
   * I also changed the API ;)
   */

  static FirebaseOptions web = FirebaseOptions(
    apiKey           : Credential.WEB_API_KEY,
    appId            : Credential.WEB_APP_ID,
    messagingSenderId: Credential.MESSAGING_SENDER_ID,
    projectId        : Credential.PROJECT_ID,
    authDomain       : Credential.WEB_AUTH_DOMAIN,
    storageBucket    : Credential.STORAGE_BUCKET,
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey           : Credential.ANDROID_API_KEY,
    appId            : Credential.ANDROID_APP_ID,
    messagingSenderId: Credential.MESSAGING_SENDER_ID,
    projectId        : Credential.PROJECT_ID,
    storageBucket    : Credential.STORAGE_BUCKET,
  );
}
